/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MaliciousContract } from "./MaliciousContract";
export type { SimpleSwap } from "./SimpleSwap";
export type { TestToken } from "./TestToken";
export type { UpgradeableToken } from "./UpgradeableToken";
